### ISSUE TITLE
webpack问题

### ISSUE THREAD

**Issue by hequnmin** [hequnmin/admin-dental-perfect#1]
npm install webpack --save-dev后发现无法npm start启动.

```
***MBP:admin-dental-perfect minsmac$ npm start

> admin-dental-perfect@0.1.0 start /Users/minsmac/Desktop/WorkSpace/gitlab/dental-perfect/admin-dental-perfect
> roadhog server

Failed to compile.

TypeError: Cannot read property 'compilation' of undefined
    at ProgressPlugin.apply (/Users/minsmac/Desktop/WorkSpace/gitlab/dental-perfect/admin-dental-perfect/node_modules/webpack/lib/ProgressPlugin.js:121:19)
    at Compiler.apply (/Users/minsmac/Desktop/WorkSpace/gitlab/dental-perfect/admin-dental-perfect/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/minsmac/Desktop/WorkSpace/gitlab/dental-perfect/admin-dental-perfect/node_modules/af-webpack/node_modules/webpack/lib/webpack.js:33:19)
    at createCompiler (/Users/minsmac/Desktop/WorkSpace/gitlab/dental-perfect/admin-dental-perfect/node_modules/af-webpack/lib/WebpackDevServerUtils.js:108:16)
    at then.port (/Users/minsmac/Desktop/WorkSpace/gitlab/dental-perfect/admin-dental-perfect/node_modules/af-webpack/lib/dev.js:65:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hequnmin** [comment]
roadhog与webpack似乎有冲突
```
npm uninstall webpack --save-dev
npm uninstall roadhog --save-dev
npm install roadhog --save-dev
```
